### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by vlopes11** [advpl/advpl-language-server-cxx#3]
On the [commit d319aba](https://github.com/advpl/advpl-language-server-cxx/commit/25877e9220b88c3217762cbdba3829748e747499#diff-257c6c6df89f0153e8b5ef51139ef7ba), I created an English message (which IMO should be the standard language for all user messages).

For the localization I suggest the [ICU Library](http://site.icu-project.org/), it's widely used as localization framework by big players like Amazon, Apple, etc

Do you guys agree with ICU Lib?

**Comment by killerall** [comment]
I do not think it's necessary to add another library.
Boost already has a framework for this:
http://www.boost.org/doc/libs/1_64_0/libs/locale/doc/html/index.html

I chose boost as the basis for this project, because it has a lot of functionality, multi platform and well tested.
Can check for Boost locale works for us?

**Comment by vlopes11** [comment]
It will surely do the job. I don't know much of the structure of boost lib; I'll take a look at it and implement.
